name: Terraform Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      working-directory: environments/prod
      run: terraform init

    - name: Terraform Apply
      working-directory: environments/prod
      run: terraform apply -auto-approve

    - name: Sync Media to S3
      run: |
        aws s3 sync ../service-data/videos s3://${{ secrets.S3_BUCKET_NAME }}/videos --delete
        aws s3 sync ../service-data/posters s3://${{ secrets.S3_BUCKET_NAME }}/posters --delete
